name: New Selenium Test Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'  # Using 'temurin' for OpenJDK
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest  # Specify the version you need
        install-chromedriver: true

    - name: Set permissions for gradlew
      run: chmod +x selenium-test-project/gradlew # Ensure gradlew is executable

    - name: Build with Gradle
      run: cd selenium-test-project && ./gradlew build  # Run the Gradle build

    - name: Run Selenium tests
      run: cd selenium-test-project && ./gradlew clean test --scan

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: Reports/build/reports/tests/test/  # Path to test reports (adjust if necessary)
