name: Selenium Test Workflow

on:
  workflow_dispatch: 

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Using 'temurin' for OpenJDK
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Get Chrome Version
      id: chrome-version
      run: |
         CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
         echo "Chrome version: $CHROME_VERSION"
         echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV   
         
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y unzip
        # Fetch the latest ChromeDriver version matching the Chrome version
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${{ env.CHROME_VERSION%.* }})
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
    - name: Set permissions for gradlew
      run: chmod +x selenium-test-project/gradlew  # Ensure gradlew is executable

    - name: List directory structure
      run: ls -R selenium-test-project  # Check the directory structure

    - name: Build with Gradle
      run: cd selenium-test-project && ./gradlew build  # Change to the correct directory

    - name: Run Selenium tests
      run: cd selenium-test-project && ./gradlew clean test --scan  # Change to the correct directory

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: selenium-test-project/app/build/reports/tests/test/
