name: Selenium Test Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Using 'temurin' for OpenJDK
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Get Chrome Version
      id: chrome-version
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV   

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y unzip
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${{ env.CHROME_VERSION%.* }})
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set permissions for gradlew
      run: chmod +x ./gradlew  # Ensure gradlew is executable

    - name: List directory structure
      run: ls -R  # Check the directory structure to ensure paths are correct

    - name: Build with Gradle
      run: ./gradlew build  # Run the Gradle build

    - name: Run Selenium tests
      run: ./gradlew clean test --scan  # Run the Selenium tests and generate a build scan

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests/test/  # Path to test reports (adjust if necessary)
