name: Selenium Test Workflow

on:
  workflow_dispatch: 

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'  # or 'temurin' for OpenJDK
        cache: gradle

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Get Chrome Version
      id: chrome-version
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y unzip
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Add Chrome and ChromeDriver to PATH
      run: |
        echo 'CHROME_BIN=/usr/bin/google-chrome' >> $GITHUB_ENV
        echo 'CHROME_DRIVER=/usr/local/bin/chromedriver' >> $GITHUB_ENV

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Set permissions for gradlew
      run: chmod +x selenium-test-project/gradlew  # Ensure gradlew is executable
    
    - name: List directory structure
      run: ls -R selenium-test-project  # Check the directory structure
      
    - name: Run Selenium tests
      run: cd selenium-test-project && ./gradlew clean test --scan

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: selenium-test-project/build/reports/tests/test/
